import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createProcess,reduceProcess,assertProcess,STAGES,METHODS,latestAttempt,legacyProjection} from '../runtime/dairy-process-core.mjs';
const initial=()=>createProcess();
function cmd(s,type,values={}){return reduceProcess(s,{type,...values})}
function runTo(s,target){s=cmd(s,'PLAY');s=cmd(s,'AUTO',{value:true});for(let i=0;i<400&&s.batches[s.active].stage<target;i++)s=cmd(s,'TICK',{seconds:1});assert.equal(s.batches[s.active].stage,target);return s}
function analyse(s,phase,methods,outcome='PASS') {const sampleId=s.active+'-S-'+phase;if(s.samples[sampleId].custody==='AWAITING_RECEPTION')s=cmd(s,'RECEIVE_SAMPLE',{sampleId});
 for(const method of methods){s=cmd(s,'START_TEST',{sampleId,method,outcome});for(let i=0;i<60&&latestAttempt(s.samples[sampleId],method).status==='RUNNING';i++)s=cmd(s,'TICK',{seconds:1});}return s}
function approve(s,gate){return cmd(s,'APPROVE',{gate,actor:'QUALITY-01'})}
function finished(){let s=runTo(initial(),5);s=analyse(s,'raw',['temperature','inhibitors']);s=approve(s,'receipt');s=runTo(s,7);s=analyse(s,'raw',['composition']);s=approve(s,'manufacture');s=runTo(s,10);s=analyse(s,'finished',['microbiology','packaging']);s=approve(s,'dispatch');return runTo(s,13)}
test('initial state separates species and preserves totals',()=>{const s=initial();assert(assertProcess(s));assert.equal(Object.keys(s.batches).length,2);assert.notEqual(...Object.values(s.batches).map(b=>b.species))});
test('invalid parameters rejected',()=>{assert.throws(()=>createProcess({bovineL:-1}));assert.throws(()=>createProcess({yieldRatio:1.5}));assert.throws(()=>createProcess({epoch:'<script>'}));});
test('view selection never progresses a task',()=>{const s=initial(),n=cmd(s,'SELECT',{id:'DEMO-OVI'});assert.equal(n.batches['DEMO-BOV'].stage,0);assert.equal(n.active,'DEMO-OVI')});
test('pause and bounded ticks',()=>{let s=initial();s=cmd(s,'START_TASK');const n=cmd(s,'TICK',{seconds:10});assert.equal(n.batches[n.active].task.elapsed,0);assert.throws(()=>cmd(s,'TICK',{seconds:1e9}));});
test('cannot skip reception or accept without tests',()=>{let s=runTo(initial(),5);assert.throws(()=>approve(s,'receipt'));assert.throws(()=>cmd(s,'START_TASK'));assert.equal(s.batches[s.active].inventory.tankerL,12000)});
test('sample custody required before analysis',()=>{const s=runTo(initial(),5);assert.throws(()=>cmd(s,'START_TEST',{sampleId:s.active+'-S-raw',method:'temperature'}))});
test('receiving acceptance is not manufacture approval',()=>{let s=runTo(initial(),5);s=analyse(s,'raw',['temperature','inhibitors']);s=approve(s,'receipt');assert(s.batches[s.active].gates.receipt);assert.equal(s.batches[s.active].gates.manufacture,null);s=runTo(s,7);assert.throws(()=>approve(s,'manufacture'))});
test('analysis has nonzero duration and cannot be duplicated',()=>{let s=runTo(initial(),5);const sampleId=s.active+'-S-raw';s=cmd(s,'RECEIVE_SAMPLE',{sampleId});s=cmd(s,'START_TEST',{sampleId,method:'temperature'});assert.equal(latestAttempt(s.samples[sampleId],'temperature').status,'RUNNING');assert.throws(()=>cmd(s,'START_TEST',{sampleId,method:'temperature'}));});
test('full journey, genealogy, delivery residual and material balance',()=>{const s=finished(),b=s.batches[s.active],v=b.inventory;assert.equal(b.stage,13);assert.equal(b.lotIds.length,5);assert.equal(v.deliveredL,11520);assert.equal(v.packedL,120);assert.equal(v.lossL,360);assert.equal(v.dispatchedPallets,16);assert(assertProcess(s));assert.equal(s.lots[b.lotIds[4]].parentIds[0],b.lotIds[3]);});
test('segregated milk never reaches the tanker',()=>{let s=cmd(initial(),'SEGREGATE',{litres:50});s=runTo(s,5);assert.equal(s.batches[s.active].inventory.tankerL,11950);assert.equal(s.batches[s.active].inventory.withheldL,50);assert(assertProcess(s));});
test('failure holds only affected species and cannot be cleared blindly',()=>{let s=runTo(initial(),5);s=analyse(s,'raw',['temperature'],'FAIL');assert(s.batches[s.active].hold);assert(!s.batches['DEMO-OVI'].hold);assert.throws(()=>cmd(s,'RESOLVE',{incidentId:s.incidents[0].id,note:'Sin investigación',actor:'QUALITY-01'}));});
test('retest requires note, appends attempt, then documented closure',()=>{let s=runTo(initial(),5);s=analyse(s,'raw',['temperature'],'FAIL');const sampleId=s.active+'-S-raw';assert.throws(()=>cmd(s,'START_TEST',{sampleId,method:'temperature'}));s=cmd(s,'START_TEST',{sampleId,method:'temperature',note:'Investigación demo registrada'});s=cmd(s,'TICK',{seconds:10});s=cmd(s,'RESOLVE',{incidentId:s.incidents[0].id,note:'Reensayo y causa verificados en demo',actor:'QUALITY-01'});assert(!s.batches[s.active].hold);assert.equal(s.samples[sampleId].attempts[0].status,'FAIL');assert.equal(s.samples[sampleId].attempts[1].status,'PASS');});
test('invalid instrument stops running analysis',()=>{let s=runTo(initial(),5);const sampleId=s.active+'-S-raw';s=cmd(s,'RECEIVE_SAMPLE',{sampleId});s=cmd(s,'START_TEST',{sampleId,method:'temperature'});s=cmd(s,'EQUIPMENT',{id:'THERMOMETER',ready:false,note:'Fallo de verificación'});assert.equal(latestAttempt(s.samples[sampleId],'temperature').status,'INVALID');assert.throws(()=>cmd(s,'START_TEST',{sampleId,method:'temperature',note:'Nueva verificación'}));});
test('post production hold never destroys physical inventory or previous decisions',()=>{let s=finished(),v=structuredClone(s.batches[s.active].inventory),len=s.decisions.length;s=cmd(s,'HOLD',{note:'Incidencia tras expedición'});assert.deepEqual(s.batches[s.active].inventory,v);assert.equal(s.decisions.length,len);assert.equal(s.batches[s.active].gates.dispatch,null);assert.equal(s.events.at(-1).type,'POST_DISPATCH_ALERT');});
test('duplicate command cannot double production',()=>{let s=initial();s=cmd(s,'SEGREGATE',{litres:100,commandId:'idempotent'});const n=cmd(s,'SEGREGATE',{litres:200,commandId:'idempotent'});assert.equal(n,s)});
test('legacy projection is explicitly derived',()=>{const s=finished(),p=legacyProjection(s);assert.equal(p.derivedFrom,'gaza:process-flow:v2');assert.equal(p.status,'COMPLETE');assert.equal(p.inventory.dispatchedPallets,16)});
test('corrupt quantity, mixed genealogy and invalid stage fail validation',()=>{const s=finished();s.batches[s.active].inventory.tankL=-1;assert.throws(()=>assertProcess(s));const t=finished();t.lots[t.batches[t.active].lotIds[1]].species='OVINE';assert.throws(()=>assertProcess(t));});
test('quality role is needed for approval',()=>{let s=runTo(initial(),5);s=analyse(s,'raw',['temperature','inhibitors']);assert.throws(()=>cmd(s,'APPROVE',{gate:'receipt',actor:'DRIVER-01'}))});
test('rejected custody must be recollected and then reviewed',()=>{let s=runTo(initial(),5);const sampleId=s.active+'-S-raw';s=cmd(s,'RECEIVE_SAMPLE',{sampleId,accept:false});s=cmd(s,'REPLACE_SAMPLE',{sampleId,note:'Recoger muestra con precinto correcto'});s=cmd(s,'RECEIVE_SAMPLE',{sampleId});s=cmd(s,'RESOLVE',{incidentId:s.incidents[0].id,note:'Nueva toma verificada en demo',actor:'QUALITY-01'});assert(!s.batches[s.active].hold);assert.equal(s.samples[sampleId].rejections.length,1)});
test('same equipment cannot serve two tasks at once',()=>{let s=initial();s=cmd(s,'START_TASK');s=cmd(s,'SELECT',{id:'DEMO-OVI'});assert.throws(()=>cmd(s,'START_TASK'));});
test('running manufacturing stays stopped after closing hold until reapproved',()=>{let s=runTo(initial(),5);s=analyse(s,'raw',['temperature','inhibitors']);s=approve(s,'receipt');s=runTo(s,7);s=analyse(s,'raw',['composition']);s=approve(s,'manufacture');s=cmd(s,'START_TASK');s=cmd(s,'TICK',{seconds:2});s=cmd(s,'HOLD',{note:'Control adicional en proceso'});const progress=s.batches[s.active].task.elapsed;s=cmd(s,'RESOLVE',{incidentId:s.incidents[0].id,note:'Investigación documentada en demo',actor:'QUALITY-01'});s=cmd(s,'TICK',{seconds:3});assert.equal(s.batches[s.active].task.elapsed,progress);s=approve(s,'receipt');s=approve(s,'manufacture');s=cmd(s,'TICK',{seconds:1});assert(s.batches[s.active].task.elapsed>progress)});
test('raw material holds the tanker resource until unloaded',()=>{let s=runTo(initial(),5);s=cmd(s,'SELECT',{id:'DEMO-OVI'});s=runTo(s,3);assert.throws(()=>cmd(s,'START_TASK'));});
test('equipment no-op cannot silently revoke valid measurements',()=>{let s=runTo(initial(),5);s=analyse(s,'raw',['temperature']);assert.throws(()=>cmd(s,'EQUIPMENT',{id:'THERMOMETER',ready:true,note:'Mismo estado sin incidencia'}));assert.equal(latestAttempt(s.samples[s.active+'-S-raw'],'temperature').status,'PASS')});
