import test from 'node:test';
import assert from 'node:assert/strict';
import {initialState,reduce,planReady,assertState,validateState,gateEligibility,taskEligibility,testEligibility,latestTest,visualSnapshot} from '../runtime/processes/ledger.mjs';
import {GATES,TASKS,TESTS} from '../runtime/processes/catalog.mjs';
const id='SIM-BOV-001';
const create=()=>initialState({lots:[{id,species:'BOVINE',plannedL:9600,excludedL:120}]});
const act=(s,a)=>reduce(s,{lotId:id,...a});
function drive(s,predicate,{review=true,max=400}={}){
 for(let n=0;n<max;n++){
  if(predicate(s))return s;
  s=planReady(s);
  if(review)for(const lotId of Object.keys(s.lots))for(const gate of Object.keys(GATES))if(s.lots[lotId].gates[gate].status!=='APPROVED'&&gateEligibility(s,lotId,gate).ok)s=reduce(s,{type:'REVIEW_GATE',lotId,gate,reviewer:'SIM-QA-01'});
  s=reduce(s,{type:'TICK',seconds:1});assertState(s);
 }
 throw new Error('Condition not reached');
}
const raw=s=>s.lots[id].samples.raw;
const packed=s=>s.lots[id].tasks['PLANT.PACK'].status==='DONE';
test('initial two independent species and zero invented production',()=>{const s=initialState();assert.equal(Object.keys(s.lots).length,2);for(const l of Object.values(s.lots)){assert.equal(l.mass.producedL,0);assert.equal(l.genealogy.length,1)}assertState(s)});
test('no task may skip predecessors',()=>{const s=create();assert.equal(taskEligibility(s,id,'PLANT.PROCESS').ok,false);const n=act(s,{type:'START_TASK',taskId:'PLANT.PROCESS'});assert.equal(n.lots[id].tasks['PLANT.PROCESS'].status,'PENDING');assert.equal(n.events.at(-1).type,'ACTION_BLOCKED')});
test('immutability of rejected and accepted transitions',()=>{const s=create(),before=JSON.stringify(s);act(s,{type:'START_TASK',taskId:'FARM.BIOSECURITY'});assert.equal(JSON.stringify(s),before)});
test('task requires simulation time; not button or frame count',()=>{let s=act(create(),{type:'START_TASK',taskId:'FARM.BIOSECURITY'});s=act(s,{type:'TICK',seconds:5});assert.equal(s.lots[id].tasks['FARM.BIOSECURITY'].status,'RUNNING');s=act(s,{type:'TICK',seconds:1});assert.equal(s.lots[id].tasks['FARM.BIOSECURITY'].status,'DONE')});
test('shared equipment prevents simultaneous double booking',()=>{let s=initialState();s=reduce(s,{type:'START_TASK',lotId:id,taskId:'FARM.BIOSECURITY'});s=reduce(s,{type:'START_TASK',lotId:'SIM-OVI-001',taskId:'FARM.BIOSECURITY'});assert.equal(s.lots['SIM-OVI-001'].tasks['FARM.BIOSECURITY'].status,'PENDING')});
test('milk produced segregates excluded source without blocking unrelated lot',()=>{const s=drive(create(),x=>x.lots[id].tasks['FARM.MILKING'].status==='DONE');assert.equal(s.lots[id].mass.segregatedL,120);assert.equal(s.lots[id].mass.farmTankL,9480);assert.equal(s.lots[id].holds,false)});
test('no analysis without sample',()=>{assert.equal(testEligibility(create(),id,'RAW.COMPOSITION').ok,false)});
test('no discharge without first review',()=>{const s=drive(create(),x=>Object.keys(x.lots[id].samples).includes('raw'),{review:false});assert.equal(taskEligibility(s,id,'RECEPTION.UNLOAD').ok,false);assert.equal(s.lots[id].mass.siloL,0)});
test('microbiology is not required before accepting raw reception',()=>{const s=drive(create(),x=>gateEligibility(x,id,'admission').ok,{review:false});assert.equal(s.lots[id].tests.some(x=>x.testId==='FINAL.MICRO'),false);assert(gateEligibility(s,id,'admission').ok)});
test('approval is not automatic in autoplan',()=>{let s=act(create(),{type:'AUTO',enabled:true});for(let i=0;i<200;i++)s=act(s,{type:'TICK',seconds:1});assert.equal(s.lots[id].gates.admission.status,'PENDING');assert.equal(s.lots[id].mass.siloL,0)});
test('manufacturing and dispatch are separate decisions',()=>{const s=drive(create(),x=>x.lots[id].tasks['PLANT.PROCESS'].status==='RUNNING');assert.equal(s.lots[id].gates.admission.status,'APPROVED');assert.equal(s.lots[id].gates.manufacturing.status,'APPROVED');assert.equal(s.lots[id].gates.dispatch.status,'PENDING')});
test('completion creates finished sample with parent batch',()=>{const s=drive(create(),packed);assert.equal(s.lots[id].samples.finished.nodeId,id+'-PACK');const nodes=s.lots[id].genealogy;assert.deepEqual(nodes.find(n=>n.id===id+'-PACK').parentIds,[id+'-BATCH'])});
test('final assay cannot be instantly passed',()=>{let s=drive(create(),packed);s=act(s,{type:'START_TEST',testId:'FINAL.MICRO',scenarioResult:'PASS'});const t=latestTest(s.lots[id],'FINAL.MICRO');assert.equal(t.result,null);s=act(s,{type:'TICK',seconds:54});assert.equal(latestTest(s.lots[id],'FINAL.MICRO').status,'RUNNING');s=act(s,{type:'TICK',seconds:1});assert.equal(latestTest(s.lots[id],'FINAL.MICRO').result,'PASS')});
test('adverse result is retained, re-test requires reason',()=>{let s=drive(create(),x=>!!raw(x),{review:false});s=act(s,{type:'START_TEST',testId:'RAW.INHIBITORS',scenarioResult:'FAIL'});s=act(s,{type:'TICK',seconds:14});assert(s.lots[id].holds);const n=act(s,{type:'START_TEST',testId:'RAW.INHIBITORS',scenarioResult:'PASS'});assert.equal(n.lots[id].tests.length,s.lots[id].tests.length);assert.equal(n.events.at(-1).type,'ACTION_BLOCKED')});
test('failed results never overwritten by justified retest',()=>{let s=drive(create(),x=>!!raw(x),{review:false});s=act(s,{type:'START_TEST',testId:'RAW.INHIBITORS',scenarioResult:'FAIL'});s=act(s,{type:'TICK',seconds:14});s=act(s,{type:'START_TEST',testId:'RAW.INHIBITORS',scenarioResult:'PASS',reason:'Repeat after documented corrective evidence'});s=act(s,{type:'TICK',seconds:14});const all=s.lots[id].tests.filter(t=>t.testId==='RAW.INHIBITORS');assert.equal(all.length,2);assert.equal(all[0].result,'FAIL');assert.equal(all[1].result,'PASS');assert.equal(all[1].replaces,all[0].id);assert(s.lots[id].holds)});
test('hold pauses affected process without erasing quantities',()=>{let s=drive(create(),packed);const mass=structuredClone(s.lots[id].mass);s=act(s,{type:'INCIDENT',reason:'Packaging deviation in scenario'});s=act(s,{type:'TICK',seconds:20});assert.deepEqual(s.lots[id].mass,mass)});
test('hold correction requires evidence and human review',()=>{let s=act(create(),{type:'INCIDENT',reason:'Cooling incident'});s=act(s,{type:'REVIEW_HOLD',reviewer:'SIM-QA-01'});assert(s.lots[id].holds);const issue=s.lots[id].issues[0];s=act(s,{type:'CORRECT_ISSUE',issueId:issue.id,evidence:'Repair inspected and temperature records attached'});assert(s.lots[id].holds);s=act(s,{type:'REVIEW_HOLD',reviewer:'SIM-QA-01'});assert(!s.lots[id].holds)});
test('hold after delivery flags recall and never rewinds delivery',()=>{let s=drive(create(),x=>x.lots[id].tasks['DELIVERY.ARRIVE'].status==='DONE');const before=s.lots[id].mass.deliveredL;s=act(s,{type:'INCIDENT',reason:'Result investigation after delivery'});assert(s.lots[id].recall);assert.equal(s.lots[id].mass.deliveredL,before)});
test('metrology prevents starting tests',()=>{let s=drive(create(),x=>!!raw(x),{review:false});s=act(s,{type:'EQUIPMENT',resource:'inhibitor-reader',valid:false,reason:'Verification expired'});assert.equal(testEligibility(s,id,'RAW.INHIBITORS').ok,false)});
test('metrology change invalidates ongoing result',()=>{let s=drive(create(),x=>!!raw(x),{review:false});s=act(s,{type:'START_TEST',testId:'RAW.INHIBITORS',scenarioResult:'PASS'});s=act(s,{type:'EQUIPMENT',resource:'inhibitor-reader',valid:false,reason:'Calibration anomaly'});s=act(s,{type:'TICK',seconds:14});assert.equal(latestTest(s.lots[id],'RAW.INHIBITORS').result,'INVALID')});
test('sample custody stops analytical eligibility',()=>{let s=drive(create(),x=>!!raw(x),{review:false});s=act(s,{type:'SAMPLE_CUSTODY',sample:'raw',status:'REJECTED',reason:'Broken sample seal'});assert(s.lots[id].holds);assert.equal(testEligibility(s,id,'RAW.INHIBITORS').ok,false)});
test('full run conserves mass including partial pallets',()=>{const s=drive(create(),x=>x.lots[id].tasks['DELIVERY.ARRIVE'].status==='DONE');const m=s.lots[id].mass;assert.equal(m.producedL,9600);assert(m.deliveredL>0);assert(m.packedL<s.config.palletCapacityL);assert.equal(m.segregatedL+m.lossL+m.deliveredL+m.packedL,9600);assertState(s)});
test('two species finish without merging origin or parallel resource conflicts',()=>{const s=drive(initialState(),x=>Object.values(x.lots).every(l=>l.tasks['DELIVERY.ARRIVE'].status==='DONE'),{max:800});assertState(s);for(const l of Object.values(s.lots))assert(l.genealogy.every(n=>n.species===l.species))});
test('invalid imported state fails closed',()=>{for(const x of [null,{},[],{schemaVersion:2,provenance:'REAL_AUTHORIZED'}, {...create(),clock:{seconds:NaN}}])assert.equal(validateState(x),false)});
test('non-finite and negative quantities are rejected',()=>{for(const n of [-1,NaN,Infinity,0])assert.throws(()=>initialState({lots:[{id,species:'BOVINE',plannedL:n,excludedL:0}]}))});
test('invalid actor cannot release gate',()=>{let s=drive(create(),x=>gateEligibility(x,id,'admission').ok,{review:false});s=act(s,{type:'REVIEW_GATE',gate:'admission',reviewer:'SIM-FARM-01'});assert.equal(s.lots[id].gates.admission.status,'PENDING')});
test('negative tick rejected',()=>assert.throws(()=>act(create(),{type:'TICK',seconds:-1})));
test('visual state only reports moving vehicle for active authorized task',()=>{let s=drive(create(),x=>x.lots[id].tasks['LOGISTICS.TRANSIT'].status==='RUNNING');assert(visualSnapshot(s,id).tankerMoving);s=act(s,{type:'INCIDENT',reason:'Transport delay review'});assert(!visualSnapshot(s,id).tankerMoving)});
test('discovery snapshot does not change process state',()=>{const s=create(),before=JSON.stringify(s);visualSnapshot(s,id);assert.equal(JSON.stringify(s),before)});
test('large and small timestep equivalent for timed work',()=>{let s=act(create(),{type:'START_TASK',taskId:'FARM.BIOSECURITY'});const a=act(s,{type:'TICK',seconds:6});for(let i=0;i<6;i++)s=act(s,{type:'TICK',seconds:1});assert.deepEqual(a.lots,s.lots)});
