import React,{useEffect,useMemo,useState} from 'https://esm.sh/react@19.1.1';
import{createRoot}from'https://esm.sh/react-dom@19.1.1/client';
import htm from'https://esm.sh/htm@3.1.1';
import{CursorGrid,DecryptedText,ElectricBorder,TiltCard,PixelTransition,ProximityDock,LetterGlitch,Crosshair,RadarScope}from'./rb-wow.js';
const html=htm.bind(React.createElement);

const systems=[['CTRL','KNX · DALI · Gira · Logic'],['AV','DSP · Matrix · Dante'],['NET','TCP/IP · VLAN · PoE · VPN'],['CODE','JS · Python · APIs · Git'],['AI','Agents · OmniRoute · OpenClaw'],['OPS','CAD · QA · Commissioning']];
const projects=[
{id:'GAZA',title:'GAZA Operations Intelligence',tag:'INDUSTRIAL DIGITAL TWIN',stack:'THREE.JS · GIS · WEATHER · IT/OT · AI',copy:'Control Tower con Digital Twin 3D, GIS, clima espacial, ASRS, expediciones, flota y decisión humana.',href:'../gaza/',signal:'LIVE / ITERATING',color:'#5b8cff'},
{id:'MAR',title:'Mar Salada · Club del Mar',tag:'SYSTEMS INTEGRATION',stack:'KNX · DALI · DSP · ECLER · LYNX',copy:'Audio, iluminación y automatización integrados desde arquitectura hasta commissioning y documentación.',href:'../../index.html#projects',signal:'FIELD SYSTEM',color:'#55d6be'},
{id:'RHB',title:'RHB STUDIO',tag:'ENGINEERING PLATFORM',stack:'AGENTS · CAD · AUTOMATION · LOCAL-FIRST',copy:'Plataforma interna para levantamiento, CAD, documentación, presupuestos, renders y automatización por agentes.',href:'../../index.html#ventures',signal:'LOCAL RUNTIME',color:'#ffbd5a'}];

function useTelemetry(){const[t,setT]=useState(0);useEffect(()=>{const id=setInterval(()=>setT(x=>x+1),700);return()=>clearInterval(id)},[]);return useMemo(()=>({load:48+(t*7)%37,latency:11+(t*13)%29,tasks:6+(t*3)%11,t}),[t])}
function Boot(){const[show,setShow]=useState(true);useEffect(()=>{const t=setTimeout(()=>setShow(false),2350);return()=>clearTimeout(t)},[]);if(!show)return null;return html`<div className="boot"><div className="bootBox"><p>HL//SYSTEM BOOT</p><code>LOAD identity ............ OK<br/>MAP disciplines .......... OK<br/>VERIFY field stack ....... OK<br/>SYNC portfolio nodes ..... OK<br/>OPEN operator interface .. READY</code><div className="bootbar"><i></i></div></div></div>`}
function App(){const tel=useTelemetry();const go=id=>document.getElementById(id)?.scrollIntoView({behavior:'smooth'});const dock=[['TOP','⌁','top'],['SYSTEMS','⌬','systems'],['PROJECTS','▦','projects'],['CONTACT','◉','contact']].map(([label,icon,id])=>({label,icon,onClick:()=>go(id)}));dock.push({label:'GAZA',icon:'G',onClick:()=>location.href='../gaza/'});
return html`<div className="wow"><${Boot}/><${Crosshair}/>
<div className="bg"><${CursorGrid}/><${LetterGlitch} density=${720} opacity=${.12}/></div><div className="scan"></div>
<header><a className="mark" href="../../index.html">HL//SYS</a><div className="read"><span>PORTFOLIO NODE</span><b>ONLINE</b></div><div className="read"><span>LATENCY</span><b>${tel.latency} ms</b></div><div className="read"><span>THREADS</span><b>${tel.tasks}</b></div><a className="classic" href="../../index.html">CLASSIC ↗</a></header>
<main>
<section id="top" className="hero"><div className="heroCopy"><p className="micro">TECHNICAL IDENTITY / SYSTEMS ENGINEERING / 2026</p><div className="idtag">IDENTITY RESOLUTION</div><h1><${DecryptedText} text="HÉCTOR"/><br/><span><${DecryptedText} text="LOBATO" speed=${34}/></span></h1><div className="rail"><span>SYSTEMS INTEGRATION</span><i>×</i><span>AUTOMATION</span><i>×</i><span>IT/OT</span><i>×</i><span>AV</span><i>×</i><span>AI</span></div><div className="signalLine"><b>CTRL</b><i></i><b>NET</b><i></i><b>AV</b><i></i><b>CODE</b><i></i><b>AI</b><i></i><b>OPS</b></div><p className="lead">Diseño la arquitectura que conecta <b>espacio físico, automatización, redes, audiovisual y software</b>. El CV se comporta como una interfaz: sistema, señales, estados y proyectos verificables.</p><div className="actions"><a href="#projects">ENTER PROJECT MATRIX</a><a className="ghost" href="mailto:lobatohernandezhector@gmail.com">OPEN CHANNEL</a></div><div className="metrics"><div><small>SYSTEM LOAD</small><b>${tel.load}%</b><i style=${{width:tel.load+'%'}}></i></div><div><small>MODE</small><b>FIELD + DIGITAL</b><span>architecture → commissioning</span></div><div><small>STATE</small><b>BUILD / TEST / FIX</b><span>cross-discipline execution</span></div></div></div>
<div className="heroVisual"><div className="radarWrap"><${RadarScope}/><span>DISCIPLINE RADAR / LIVE TOPOLOGY</span></div><${ElectricBorder} className="profile"><div className="photo"><img src="../../assets/hector-profile.png" alt="Héctor Lobato"/><div className="overlay"></div><div className="corner a">ID_01</div><div className="corner b">SYS/ENG</div><div className="profileTag"><span>NODE</span><b>HLOBATO</b><em>AUTHENTICATED</em></div></div><//><div className="chip c1"><span>CTRL</span><b>KNX / DALI</b></div><div className="chip c2"><span>SIGNAL</span><b>DSP / AV</b></div><div className="chip c3"><span>NET</span><b>IT / OT</b></div><div className="chip c4"><span>FLOW</span><b>AI / AGENTS</b></div></div></section>

<section id="systems" className="section"><div className="index">01 / SYSTEM TOPOLOGY</div><div className="sectionHead"><h2>NO SILOS.<br/><span>ONE SYSTEM.</span></h2><p>Cada disciplina es un nodo de una topología única. Mueve el cursor: el CV reacciona como una interfaz técnica, no como un documento.</p></div><div className="nodes">${systems.map(([n,d],i)=>html`<${TiltCard} key=${n}><article className="node"><span>${String(i+1).padStart(2,'0')}</span><h3>${n}</h3><p>${d}</p><div className="bars"><i></i><i></i><i></i><i></i></div></article><//>`)}</div></section>

<section id="projects" className="section"><div className="index">02 / PROJECT MATRIX</div><div className="sectionHead"><h2>PROJECTS AS<br/><span>ACTIVE SYSTEMS.</span></h2><p>Hover/focus cambia de identidad a arquitectura. La transición pixelada separa “qué es” de “cómo funciona”.</p></div><div className="projectGrid">${projects.map(p=>html`<${PixelTransition} key=${p.id} color=${p.color} front=${html`<article className="face"><div className="top"><b>${p.id}</b><em>${p.signal}</em></div><h3>${p.title}</h3><p>${p.tag}</p><div className="laser"></div><small>HOVER / FOCUS TO DECODE</small></article>`} back=${html`<article className="face decoded"><span>${p.stack}</span><h3>${p.title}</h3><p>${p.copy}</p><a href=${p.href}>OPEN SYSTEM ↗</a></article>`}/>` )}</div></section>

<section className="section"><div className="index">03 / ENGINEERING LOG</div><div className="logGrid"><article className="mission"><span>MISSION</span><h2>FROM AMBIGUITY<br/>TO OPERABLE SYSTEM.</h2><p>Survey → architecture → integration → commissioning → diagnostics → documentation → continuous improvement.</p></article><article className="terminal"><div><i></i><i></i><i></i><span>hl_engineering.log</span></div><code>22:30:01  LOAD context_model ........ OK<br/>22:30:02  MAP interfaces ........... OK<br/>22:30:03  CHECK constraints ......... OK<br/>22:30:05  ROUTE systems ............. OK<br/>22:30:06  VERIFY field_state ........ ACTIVE<br/>22:30:08  COMMISSION result ......... READY<br/><br/><b>&gt; waiting for next impossible brief_</b></code></article></div></section>

<section id="contact" className="contact"><p className="micro">OPEN CHANNEL / OPPORTUNITY INTAKE</p><h2><${DecryptedText} text="BUILD SOMETHING DIFFICULT." animateOn="hover" speed=${22}/></h2><p>Integración, automatización, AV, operaciones, producto técnico o sistemas con IA aplicada.</p><a href="mailto:lobatohernandezhector@gmail.com">lobatohernandezhector@gmail.com ↗</a></section>
</main><${ProximityDock} items=${dock}/></div>`}
createRoot(document.getElementById('root')).render(html`<${App}/>`);
