/** Site-study coordinates only. Public function != measured location, equipment or installed capacity. */
import {TASKS,GATES} from '../processes/catalog.mjs';
import {validateState,taskEligibility,gateEligibility} from '../processes/ledger.mjs';
export const BOUNDARY='Planta descompuesta · distribución propuesta. Fuentes públicas acreditan funciones concretas, no coordenadas, P&ID, turnos ni equipamiento exacto. SIM: sin control industrial.';
export const SOURCES=Object.freeze({
 photo:{title:'Capturas del usuario · Los Pinares, Coreses · marzo 2025',url:null,kind:'PHOTO_REFERENCE',supports:'Fachada roja/gris, testero rotulado, rótulo lateral, oficinas exteriores, vallado y funciones de accesos 1 y 2.',limits:'Fotointerpretación sin escala ni orientación geodésica; interiores no visibles.'},
 gaza:{title:'GAZA · I+D+i / GAZACONTROL',url:'https://www.lechegaza.com/I%2BD%2Bi.html',kind:'PUBLIC_REFERENCE',supports:'Integración de procesos, CIP, automatización y logística; mejora continua.',limits:'No acredita las marcas/modelos, recetas ni la disposición de la línea representada.'},
 quality:{title:'GAZA · Calidad',url:'https://www.lechegaza.com/calidad-gaza.html',kind:'PUBLIC_REFERENCE',supports:'Trazabilidad y Plan Gaza de Aseguramiento de la Calidad.',limits:'Sin organigrama, localización de salas ni plan analítico completo.'},
 asrs:{title:'Esnova · almacén para Leche Gaza',url:'https://www.linkedin.com/posts/esnova_almac%C3%A9n-autom%C3%A1tico-fabricado-por-esnova-racks-activity-6778236573809987584-akRa',kind:'PUBLIC_REFERENCE',supports:'Almacén automático con 9 niveles de carga; carros Signode Storfast.',limits:'Número de calles, palés, capacidad, coordenadas y lógica interna no publicados en esta referencia.'},
 utilities:{title:'Veolia · caso Leche Gaza',url:'https://www.veolia.es/casos-exito/leche-gaza',kind:'PUBLIC_REFERENCE',supports:'Sala de calderas de vapor, potabilización, EDARI y gestión de residuos.',limits:'Referencia de proyecto, no inventario ni topología operativa actual.'},
 erp:{title:'Solmicro · referencia cliente Leche Gaza',url:'https://www.solmicro.com/clientes-erp/clientes-erp-solmicro/102277-leche-gaza-zamora',kind:'PUBLIC_REFERENCE',supports:'Leche Gaza aparece como referencia de cliente ERP.',limits:'No confirma versión actual, módulos, pantallas, API ni implantación por departamento.'},
 aula:{title:'GAZA · Aula Láctea',url:'https://www.lechegaza.com/aula-lactea.html',kind:'PUBLIC_REFERENCE',supports:'Espacio educativo y visitas a fábrica con bata y gorro.',limits:'No publica la planta interior ni permite ubicarla por sí sola en el pabellón de madera.'},
 delta:{title:'GAZA · proyecto DELTA',url:'https://www.lechegaza.com/_proyectos/proyecto-delta.html',kind:'PUBLIC_REFERENCE',supports:'Proyecto de digitalización de procesos del agua en industria alimentaria.',limits:'Sin acceso a datos de agua en vivo ni automatismos reales.'},
 thermal:{title:'Tetra Pak · Long-life dairy products',url:'https://dairyprocessinghandbook.tetrapak.com/chapter/long-life-dairy-products',kind:'GENERAL_TECHNICAL_REFERENCE',supports:'Contexto de tratamiento y envasado de larga vida, no referencia de suministro a GAZA.',limits:'La sublínea térmica dibujada es genérica; no identifica receta, método ni equipo instalado en GAZA.'},
 solar:{title:'Observación del usuario · solar y silos tras el edificio',url:null,kind:'USER_REPORTED_UNVERIFIED',supports:'Solicitud de investigar las instalaciones traseras.',limits:'Google Maps no accesible en esta revisión. Sin ortofoto/contorno, número de paneles, potencia, titularidad ni coordenadas confirmados.'}
});
const area=(id,title,x,z,w,d,taskIds,evidence,steps,role,extra={})=>Object.freeze({id,title,x,z,w,d,taskIds,evidence,steps,role,geometry:'SIMULATED_LAYOUT',...extra});
export const DEPARTMENTS=Object.freeze([
 area('reception','Recepción y descarga',39,87,18,34,['RECEPTION.SAMPLE','RECEPTION.UNLOAD'],['photo','gaza'],['Identificar entrega y compartimento','Muestrear y conservar vínculo de laboratorio','Esperar aceptación de descarga','Transferir a silo compatible y registrar origen'],'SIM-RECEPTION-01',{target:'labs'}),
 area('raw','Silos y materia prima',16,87,25,34,['RECEPTION.UNLOAD','PLANT.PROCESS'],['photo','gaza'],['Conservar origen/especie','Mostrar volumen del registro','Bloquear consumo si calidad lo impide','Entregar materia prima a fabricación'],'SIM-RECEPTION-01'),
 area('process','Preparación y tratamiento',11,34,42,62,['PLANT.PROCESS'],['gaza','thermal'],['Preparación/transferencia ilustrativa','Tratamiento genérico de escenario','Enfriamiento/buffer ilustrativo','Crear lote hijo solo al completar tarea'],'SIM-PROD-01'),
 area('cip','CIP y disponibilidad',40,38,14,54,['PLANT.CIP'],['gaza'],['Comprobar circuito de escenario','Ejecutar tarea de limpieza','Registrar su terminación','Habilitar revisión de fabricación'],'SIM-CLEAN-02'),
 area('pack','Envasado y control',25,-16,44,34,['PLANT.PACK'],['gaza','quality'],['Vincular orden y envases','Ejecutar envasado del lote','Registrar producto terminado','Enviar muestra final al laboratorio'],'SIM-PACK-01'),
 area('materials','Materiales de envase',-6,-16,16,34,[],['gaza'],['Zona logística propuesta','Reserva ilustrativa de envases','No se inventa stock auxiliar','Proveedor/cantidad de envase: pendientes'],'SIM-MATERIALS-DEMO'),
 area('pallet','Paletizado y staging',17,-43,60,16,['WAREHOUSE.PUTAWAY','DISPATCH.LOAD'],['asrs'],['Representar palés completos','Conservar remanente','Asignar ubicación virtual','Esperar liberación antes de carga'],'SIM-WMS-01'),
 area('asrs','Almacén automático · 9 niveles',17,-81,60,56,['WAREHOUSE.PUTAWAY'],['asrs'],['Recepción de unidades','Lanzadera ilustrativa','Ubicaciones de entrenamiento','Sin capacidad real atribuida'],'SIM-WMS-01',{levels:9}),
 area('shipping','Muelles y expediciones',59,-76,14,62,['DISPATCH.LOAD','DELIVERY.ARRIVE'],['photo','asrs'],['Comprobar liberación de producto','Cargar palés autorizados','Conservar entrega y lote','Registrar llegada virtual sin duplicar existencias'],'SIM-SHIPPING-01'),
 area('frontdesk','Recepción de personas',-26,-29,18,14,[],['photo'],['Recibir visitas · propuesta','Relacionar acceso con destino','Registro ficticio, sin personas reales','Separar peatones y mercancía'],'SIM-RECEPTION-DESK'),
 area('administration','Administración y planificación',-26,-9,18,22,[],['photo','erp','gaza'],['Consultar entregas y órdenes derivadas','Revisar balance por lote','Consultar incidencias y registros','Exportar dossier SIM, no factura ni ERP real'],'SIM-ADMIN-DEMO'),
 area('meeting','Coordinación y calidad',-26,7,18,8,[],['quality','gaza'],['Coordinación interdepartamental propuesta','Consulta de decisiones independientes','Revisión de eventos','Sin firma/autorización real'],'SIM-QA-01'),
 area('staff','Personal y vestuarios',-26,55,18,32,[],['photo'],['Distribución propuesta en anexo','Taquillas y cambio de vestuario','Acceso higiénico ilustrativo','No acredita la sala ni el turno real'],'SIM-STAFF-DEMO'),
 area('maintenance','Mantenimiento y auxiliares',-26,90,18,30,[],['gaza','utilities'],['Revisar recursos no aptos','Consultar incidencias relacionadas','Planificar intervención propuesta','El visor no restablece equipos'],'SIM-MAINT-DEMO'),
 area('lab','Laboratorio / acceso al módulo',-7,87,15,34,['RECEPTION.SAMPLE'],['quality'],['Recepción de muestras','Ensayos y custodia en LABS','Estado de equipos compartido','Revisión en el panel común'],'SIM-LAB-01',{target:'labs'}),
 area('parking','Parking de empleados y visitas',-48,8,6,72,[],['photo'],['Parking visible en fotografías','Plazas y separación propuestas','Itinerario peatonal protegido','No son datos de ocupación real'],'SIM-ACCESS-DEMO')
]);
export const SIGN_PLACEMENTS=Object.freeze([
 {id:'logo-main',surface:'Testero corto del volumen rojo junto a acceso 1',position:[17,22,-110.35],rotationY:Math.PI,size:[20,9],evidence:'photo',positionQuality:'PHOTO_INFERRED_NOT_MEASURED'},
 {id:'logo-side',surface:'Fachada larga gris junto al pabellón de referencia',position:[-16.36,4.8,-66],rotationY:-Math.PI/2,size:[7.8,3.3],evidence:'photo',positionQuality:'PHOTO_INFERRED_NOT_MEASURED'}
]);
const byTask=Object.fromEntries(TASKS.map(t=>[t.id,t]));
export function phaseOf(s,l,id){const t=l.tasks[id],d=byTask[id];if(!t||!d)return {id,state:'UNKNOWN',progress:0};const raw=t.status==='DONE'?1:t.status==='RUNNING'?Math.max(0,Math.min(1,t.elapsed/d.durationSimSeconds)):0;let status=t.status,reason='';if(status==='RUNNING'){if(!s.equipment[d.resource]?.valid){status='UNAVAILABLE';reason='Equipo fuera de servicio'+(l.holds?' / lote retenido':'')}else if(l.holds&&!d.qualityIndependent){status='HELD';reason='Retención del lote'}else if(d.gate&&l.gates[d.gate].status!=='APPROVED'){status='WAIT_GATE';reason='Decisión revocada o pendiente'}}else if(status==='PENDING'){const e=taskEligibility(s,l.id,id);status=e.ok?'READY':'WAITING';reason=e.reason}return {id,state:status,progress:raw,reason,resource:d.resource,title:d.title,steps:d.steps};}
export function projectPlant(state,lotId){
 if(!state)return {ready:false,error:null,departments:DEPARTMENTS.map(d=>({id:d.id,status:d.taskIds.length?'NO_SCENARIO':'ILLUSTRATIVE',tasks:[]})),documents:[],lotId:null,seconds:0};
 if(!validateState(state)||!state.lots[lotId])return {ready:false,error:'Registro inválido o lote desconocido; proyección desactivada',departments:[],documents:[],lotId:null,seconds:0};
 const l=state.lots[lotId],tasks=Object.fromEntries(TASKS.map(t=>[t.id,phaseOf(state,l,t.id)])),m=l.mass;
 const departments=DEPARTMENTS.map(d=>{const list=d.taskIds.map(id=>tasks[id]);return {id:d.id,status:['HELD','UNAVAILABLE','WAIT_GATE','RUNNING','READY','WAITING','DONE'].find(x=>list.some(t=>t.state===x))||'ILLUSTRATIVE',tasks:list};});
 const docs=[
  {id:l.id+'-DELIVERY',type:'Entrada de leche',state:l.tasks['RECEPTION.UNLOAD'].status==='DONE'?'RECIBIDA':l.tasks['LOGISTICS.TRANSIT'].status==='DONE'?'EN_RECEPCIÓN':'PREVISTA',origin:l.id+'-LOAD',quantityL:m.tankerL+m.siloL+m.wipL+m.packedL+m.shippingL+m.deliveredL+m.lossL},
  {id:l.id+'-ORDER',type:'Orden de fabricación derivada',state:l.tasks['PLANT.PROCESS'].status,origin:l.id+'-SILO',quantityL:m.wipL+m.packedL+m.shippingL+m.deliveredL},
  {id:l.id+'-STOCK',type:'Existencia envasada actual',state:l.gates.dispatch.status==='APPROVED'&&!l.holds?'LIBERADA_SIM':'BLOQUEO_COMERCIAL',origin:l.id+'-PACK',quantityL:m.packedL},
  {id:l.id+'-SHIP',type:'Expedición / entrega virtual',state:l.recall?'REVISIÓN_RETIRADA':l.tasks['DELIVERY.ARRIVE'].status==='DONE'?'ENTREGADA_SIM':m.shippingL?'EN_TRANSPORTE':'PENDIENTE',origin:l.id+'-PACK',quantityL:m.shippingL+m.deliveredL}
 ];
 return {ready:true,error:null,lotId:l.id,species:l.species,seconds:state.clock.seconds,held:l.holds,tasks,departments,mass:{...m},pallets:{capacityL:state.config.palletCapacityL,stored:Math.floor(m.packedL/state.config.palletCapacityL),remainderL:m.packedL%state.config.palletCapacityL,shipped:(m.shippingL+m.deliveredL)/state.config.palletCapacityL},documents:docs,issues:l.issues.map(i=>({...i})),resources:Object.entries(state.equipment).map(([id,v])=>({id,valid:v.valid})),gates:Object.fromEntries(Object.entries(GATES).map(([id,g])=>[id,{title:g.title,status:l.gates[id].status,...gateEligibility(state,l.id,id)}])),genealogy:l.genealogy.map(n=>({...n})),events:state.events.filter(e=>!e.lotId||e.lotId===l.id).slice(-30)};
}
export function exportDossier(state,lotId){const v=projectPlant(state,lotId);if(!v.ready)throw new Error(v.error||'Sin escenario');return {schemaVersion:1,provenance:'SIMULATED_DERIVED_READ_ONLY',sourceRevision:state.revision,plan:state.config.plan,lotId,documents:v.documents,mass:v.mass,pallets:v.pallets,gates:v.gates,genealogy:v.genealogy,events:v.events,limits:'Documentos de entrenamiento. Sin facturación, datos de cliente, tarifas, firma ni conexión a ERP.'};}
