import {DEPARTMENTS,SOURCES,BOUNDARY,projectPlant,exportDossier,SIGN_PLACEMENTS} from './model.mjs';
import {buildPlantDetail} from './world.mjs';
const element=(tag,text,attrs={})=>{const el=document.createElement(tag);if(text!==null)el.textContent=text;Object.entries(attrs).forEach(([k,v])=>el.setAttribute(k,v));return el};
/** Read-only spatial/document projection. Never writes to the process store. */
export function mountPlantDetail({THREE,world,camera,controls,ensureStudy,dirty,getState,getLotId}){
 const detail=buildPlantDetail(THREE,world),host=element('section',null,{class:'panel','id':'plantDetail'});document.querySelector('aside').prepend(host);
 const css=element('style',`#plantDetail{border-color:#719b9e}#plantDetail [hidden]{display:none!important}#plantDetail *{box-sizing:border-box;overflow-wrap:anywhere}#plantDetail select{width:100%;font-size:12px}#plantDetail h3{font-size:12px;margin:12px 0 5px;color:#dae9eb}#plantDetail button{font-size:11px;padding:7px 9px}#plantDetail details{border-top:1px solid #3b5261;padding-top:8px;margin-top:9px}#plantDetail .small{font-size:10px;line-height:1.5;color:#acc4cd}#plantDetail ol{padding-left:20px;font-size:11px}#plantDetail li{margin:5px 0}#plantDetail progress{width:100%;height:9px}#plantDetail .record{padding:8px;border:1px solid #435e70;border-radius:5px;margin:7px 0;font-size:11px}#plantDetail .record strong{display:block;color:#e3eef1}#plantDetail dl{display:grid;grid-template-columns:1fr 1fr;gap:5px}#plantDetail dt{font-size:10px;color:#a8bdc9}#plantDetail dd{margin:0;font-size:13px}#plantDetail p{font-size:11px}#plantDetail .error{color:#ffcd9c}`);document.head.append(css);
 host.innerHTML='<h2>Planta / departamentos y documentación</h2><select id="plantDepartment" aria-label="Departamento de planta"></select><div class="row"><button id="plantEnter">Entrar al área</button><button id="plantPlan">Plano interior</button><button id="plantIsolate" aria-pressed="false">Aislar</button></div><label class="field"><input type="checkbox" id="plantFlow" checked> Flujos ilustrativos de producto y CIP</label><p id="plantProvenance" class="small"></p><div id="plantTaskStatus" class="status" role="status"></div><div id="plantSteps"></div><details open><summary>Qué se conoce / qué es propuesto</summary><div id="plantEvidence"></div></details><details><summary>Documentación operativa derivada</summary><p class="small">Lectura del lote común. Sin facturas, precios, clientes ni escritura en ERP.</p><div id="plantDocuments"></div><button id="plantExport">Exportar dossier SIM</button></details><details><summary>Recursos y mantenimiento</summary><div id="plantResources"></div><p class="small">Las acciones de equipo siguen en Procesos V2. Este visor no quita una retención ni repara una máquina.</p></details><details><summary>Rótulos, instalaciones traseras y precisión</summary><p>Rótulo principal en el testero rojo del acceso 1 y rótulo pequeño en lateral gris: colocación fotointerpretada, no coordenadas medidas. Se conserva el SVG existente del demostrador; no se afirma que sea un vector oficial.</p><p>Paneles solares, número/capacidad de silos y límites traseros: pendientes de contraste cartográfico. No se añaden como una implantación real inventada.</p><p class="small">Advertencia de fuentes: el enlace «ubicación» de la web de GAZA que se consultó remitía a la antigua dirección de Zamora. No se ha usado para reubicar Coreses.</p></details><a id="plantModuleLink" href="mission-control.html?view=workflow" target="_top">Abrir Workflow →</a>';
 const $=id=>host.querySelector('#'+id),select=$('plantDepartment');DEPARTMENTS.forEach(d=>select.append(element('option',d.title,{value:d.id})));
 let selected='process',isolated=false,lastKey='',signSeen=false,view=projectPlant(null,null);
 function showMapLabels(show){detail.root.traverse(o=>{if(o.isSprite)o.visible=show});detail.outdoor.traverse(o=>{if(o.isSprite)o.visible=show})}
 const statusNames={NO_SCENARIO:'Sin escenario común',ILLUSTRATIVE:'Área propuesta · sin tarea propia',HELD:'Retenido',UNAVAILABLE:'Equipo no apto',WAIT_GATE:'Decisión pendiente/revocada',RUNNING:'Trabajo activo',READY:'Disponible para iniciar',WAITING:'Esperando precedencias',DONE:'Terminado',PENDING:'Pendiente'};
 function evidence(){const d=DEPARTMENTS.find(d=>d.id===selected);$('plantProvenance').textContent=BOUNDARY;$('plantSteps').replaceChildren(element('h3',d.title+' · '+d.role));const ol=element('ol',null);d.steps.forEach(s=>ol.append(element('li',s)));$('plantSteps').append(ol);$('plantEvidence').replaceChildren(...d.evidence.map(id=>{const s=SOURCES[id],p=element('div',null,{class:'record'});p.append(element('strong',s.title),element('p',s.kind+' · '+s.supports),element('p','No acredita: '+s.limits,{class:'small'}));if(s.url)p.append(element('a','Consultar fuente',{href:s.url,target:'_blank',rel:'noopener noreferrer'}));return p}));$('plantModuleLink').href='mission-control.html?view='+(d.target||'workflow');$('plantModuleLink').textContent=d.target==='labs'?'Entrar en LABS →':'Abrir Workflow →';}
 function refresh(){const d=view.departments.find(d=>d.id===selected);$('plantTaskStatus').replaceChildren(element('div',view.error||(view.ready?view.lotId+' · '+statusNames[d?.status||'ILLUSTRATIVE']:'Sin escenario: inicia Procesos V2 en Workflow')));for(const t of d?.tasks||[]){const p=element('div',t.title+' · '+(statusNames[t.state]||t.state)+' · '+Math.round(t.progress*100)+'%');p.append(element('progress',null,{max:'1',value:String(t.progress)}));if(t.reason)p.append(element('div',t.reason,{class:'small'}));$('plantTaskStatus').append(p)}
  $('plantDocuments').replaceChildren(...view.documents.map(d=>{const p=element('div',null,{class:'record'});p.append(element('strong',d.type),element('div',d.id),element('div',d.state+' · '+d.quantityL.toLocaleString('es-ES')+' L'),element('div','Origen: '+d.origin,{class:'small'}));return p}));if(view.ready){const p=element('p',view.pallets.stored+' palés envasados completos en stock · remanente '+view.pallets.remainderL+' L · capacidad usada '+view.pallets.capacityL+' L/palé SIM');$('plantDocuments').append(p)}$('plantExport').disabled=!view.ready;
  $('plantResources').replaceChildren(...(view.resources||[]).filter(r=>!r.valid).map(r=>element('p',r.id+' · FUERA DE SERVICIO',{class:'error'})),...(view.issues||[]).filter(i=>i.status!=='CLOSED').map(i=>element('p',i.id+' · '+i.status+' · '+i.reason)));if(!view.ready)$('plantResources').append(element('p','Sin registro'));else if(!view.resources.some(r=>!r.valid)&&!view.issues.some(i=>i.status!=='CLOSED'))$('plantResources').append(element('p','Sin incidencias abiertas ni recursos marcados como no aptos en el escenario.'));
 }
 function choose(id){if(!DEPARTMENTS.some(d=>d.id===id))return;selected=id;select.value=id;detail.focus(id);evidence();refresh();dirty();}
 function open(id=selected,plan=false){if(!DEPARTMENTS.some(d=>d.id===id))id='process';choose(id);ensureStudy();const toggle=document.getElementById('cutaway');toggle.checked=true;toggle.dispatchEvent(new Event('change'));world.labels.visible=false;document.getElementById('labels').checked=false;const area=DEPARTMENTS.find(d=>d.id===id),extent=Math.max(area.w,area.d);if(plan){camera.position.set(12,330,.01);controls.target.set(12,0,0)}else{camera.position.set(area.x-extent*(id==='asrs'?.85:.5),id==='asrs'?12+extent*.45:6+extent*.9,area.z+extent*(id==='asrs'?.95:.65));controls.target.set(area.x,id==='asrs'?10:1,area.z)}controls.update();detail.focus(id);showMapLabels(plan);dirty();}
 select.onchange=()=>choose(select.value);$('plantEnter').onclick=()=>open();$('plantPlan').onclick=()=>open(selected,true);$('plantIsolate').onclick=()=>{isolated=!isolated;detail.isolate(isolated);$('plantIsolate').setAttribute('aria-pressed',String(isolated));dirty()};$('plantFlow').onchange=e=>{detail.flows(e.target.checked);dirty()};
 $('plantExport').onclick=()=>{const doc=exportDossier(getState(),getLotId()),url=URL.createObjectURL(new Blob([JSON.stringify(doc,null,2)],{type:'application/json'})),a=element('a',null,{href:url,download:'GAZA-plant-dossier-SIM.json'});a.click();setTimeout(()=>URL.revokeObjectURL(url),500)};
 choose(selected);
 return {open,inspect(data){if(data?.deptId)choose(data.deptId)},update(){detail.resolveSigns();if(!signSeen&&detail.snapshot().signsApplied){signSeen=true;dirty()}const s=getState(),id=getLotId(),key=(s?.revision??'none')+':'+id;if(key!==lastKey){lastKey=key;view=projectPlant(s,id);detail.update(view);refresh();dirty()}window.__GAZA_PLANT_DETAIL__={...detail.snapshot(),ready:view.ready,error:view.error,lotId:view.lotId,simSeconds:view.seconds,documents:view.documents,signs:SIGN_PLACEMENTS,recordSource:'READ_ONLY_PROCESS_LEDGER_V2',taskStates:view.tasks||{}}},snapshot:()=>detail.snapshot()};
}
